version: '3.1'
services:
    mongo-data:
        image: mongo
        restart: always
        networks:
            - jbtech-network
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
        ports:
          - 27017:27017
        volumes:
          - /docker-database:/data/db
    mongo-express:
        image: mongo-express
        restart: always
        networks:
            - jbtech-network
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: password
        depends_on:
          - mongo-data
    postgres-data:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "password"
        ports:
            - "15432:5432"
        volumes:
            - /docker-database:/data/db
        networks:
            - jbtech-network   
    pgadmin:
        image: dpage/pgadmin4
        environment:
          PGADMIN_DEFAULT_EMAIL: "bruno.v.andre@outlook.com"
          PGADMIN_DEFAULT_PASSWORD: "password"
        ports:
          - "16543:80"
        depends_on:
          - postgres-data
        networks:
          - jbtech-network
networks:
  jbtech-network:
    driver: bridge